version: "3"
services:
  nodejsserver1:
    build:
      context: "./nodejs-server-1"
      dockerfile: "Dockerfile"
    container_name: nodejs-server-1
    stdin_open: true
    ports:
      - 8080:8080
  nodejsserver2:
    build:
      context: "./nodejs-server-2"
      dockerfile: "Dockerfile"
    container_name: nodejs-server-2
    stdin_open: true
    ports:
      - 8081:8081
  pythonserver:
    build:
      context: "./python-server"
      dockerfile: "Dockerfile"
    container_name: python-server
    stdin_open: true
    tty: true
    ports:
      - 8082:8082
  denoserver:
    build:
      context: "./deno-server"
      dockerfile: "Dockerfile"
    container_name: deno-server
    stdin_open: true
    ports:
      - 8083:8083
  nodejsserver3:
    build:
      context: "./nodejs-server-3"
      dockerfile: "Dockerfile"
    container_name: nodejs-server-3
    stdin_open: true
    ports:
      - 8084:8084
  nodejsserver4:
    build:
      context: "./nodejs-server-4"
      dockerfile: "Dockerfile"
    container_name: nodejs-server-4
    stdin_open: true
    ports:
      - 8085:8085
