version: "3"
services:
  server1:
    build:
      context: "./node-server-1"
      dockerfile: "Dockerfile"
    container_name: nodejs-server-1
    stdin_open: true
    ports:
      - 8080:8080
  server2:
    build:
      context: "./node-server-2"
      dockerfile: "Dockerfile"
    container_name: nodejs-server-2
    stdin_open: true
    ports:
      - 8081:8081
  server4:
    build:
      context: "./python-server"
      dockerfile: "Dockerfile"
    container_name: python-server
    stdin_open: true
    tty: true
    ports:
      - 8082:8082
  denoserver:
    build:
      context: "./deno-server"
      dockerfile: "Dockerfile"
    container_name: deno-server
    stdin_open: true
    ports:
      - 8084:8084
