version: "3"
services:
  foobar:
    build:
      context: "./fooBar"
      dockerfile: "Dockerfile"
    container_name: foobar-nodejs-server
    stdin_open: true
    ports:
      - 8080:8080
  quux:
    build:
      context: "./quux"
      dockerfile: "Dockerfile"
    container_name: quux-nodejs-server
    stdin_open: true
    ports:
      - 8081:8081
  grault:
    build:
      context: "./grault"
      dockerfile: "Dockerfile"
    container_name: grault-python-server
    stdin_open: true
    tty: true
    ports:
      - 8082:8082
  waldo:
    build:
      context: "./waldo"
      dockerfile: "Dockerfile"
    container_name: waldo-deno-server
    stdin_open: true
    ports:
      - 8083:8083
  baz:
    build:
      context: "./baz"
      dockerfile: "Dockerfile"
    container_name: baz-nodejs-server
    stdin_open: true
    ports:
      - 8084:8084
  corge:
    build:
      context: "./corge"
      dockerfile: "Dockerfile"
    container_name: corge-nodejs-server
    stdin_open: true
    ports:
      - 8085:8085
  garply:
    build:
      context: "./garply"
      dockerfile: "Dockerfile"
    container_name: garply-nodejs-server
    stdin_open: true
    ports:
      - 8086:8086
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/garplyDB
    depends_on:
      - garplydb
  garplydb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: garplyDB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
